<?php
session_start();

error_reporting(E_ALL);
ini_set('display_errors', 1);
ini_set('display_startup_errors', 1);

require_once __DIR__ . '/../classes/controller/LogController.php';
require_once __DIR__ . '/../config/db_connection.php';

$logController = new LogController($mysqli);
$logController->trackVisit();



// Load all logs at the same time
$logs = $logController->showAllLogs() ?? [];

// Handle filtering and pagination
$usernameFilter = $_GET['username'] ?? '';

// Ternary if to check the current page, if it doesn't exist return page 1
$currentPage = isset($_GET['page']) ? (int)$_GET['page'] : 1;
$perPage = 15;

// Filter logs based on username provided in search bar
if ($usernameFilter) {
    $filteredLogs = [];

    foreach ($logs as $log) {
        $username = isset($log['username']) ? $log['username'] : '';
        
        if (stripos($username, $usernameFilter) !== false) {
            $filteredLogs[] = $log;
        }
    }
    
    $logs = $filteredLogs;
}

// Get total after filtering
$totalLogs = count($logs);
$totalPages = max(1, ceil($totalLogs / $perPage));
$currentPage = max(1, min($currentPage, $totalPages));

// Slice array for pagination
$offset = ($currentPage - 1) * $perPage;
$pagedLogs = array_slice($logs, $offset, $perPage);
?>

<!DOCTYPE html>
<html>

<head>
    <title>Access Log</title>
    <style>
        @import url("../css/global.css");

        /** STYLE CONTAINER */
        #logs_body_container{
            background-color: white;
            height: 100%;
            box-shadow: 0 10px 15px -3px rgb(0 0 0 / 0.1), 0 4px 6px -4px rgb(0 0 0 / 0.1);
            padding: 15px;
            box-sizing: border-box;
        }

        /** SEARCH BAR */
        .logs_search_input{
            padding: 10px 15px;
            margin-left: 15px;
            border-radius: 7px;
            border: none;
            outline: none;
            background-color:rgb(238, 238, 238);
        }

        .logs_search_btn{
            padding: 10px 15px;
            text-align: center;
            background-color: var(--primary);
            box-shadow: 0 10px 15px -3px rgb(0 0 0 / 0.1), 0 4px 6px -4px rgb(0 0 0 / 0.1);
            border-radius: 7px;
            border: none;
        }

        .logs_search_btn:hover{
            background-color: var(--primary_hover);
            cursor: pointer;
            font-weight: 400;
        }
        
        /** LOG TABLE STYLING */
        table {
            border-collapse: collapse;
            width: 98%;
            margin: 20px auto;
        }

        th,
        td {
            padding: 5px;
            border: 1px solid #ccc;
            text-align: left;
        }

        tr:nth-child(odd) {
            background-color: #f0f0f0;
        }

        tr:nth-child(even) {
            background-color: #eaeaea;
        }

        th {
            background-color: var(--primary);
        }
        
        /** PAGINATION STYLING */
        .logs_pagination_container{
            display: flex;
            align-items: center;
            gap: 10px;
            margin-top: 15px;
            margin-left: 15px;
        }

        .pagination_not_selected{
            background-color: var(--primary);
            padding: 5px;
            border-radius: 5px;
            display: flex;
            align-items: center;
            justify-content: center;
        }
        
        .pagination_selected{
            background-color: var(--primary_hover);
            padding: 5px;
            border-radius: 5px;
            display: flex;
            align-items: center;
            justify-content: center;
        }
        .log_pagination_li{
            text-align: center;
            margin-right: 5px;
        }
    </style>
</head>

<article id="logs_body_container">
    <h2 style="margin-left: 15px">Access report</h2>
    <p style="margin: 15px 0px 15px 15px;">Here you can see all the logs generated by user when accessing different pages of the portal.</p>

    <form method="get" action="">
        <input type="hidden" name="section" value="logs">
        <input type="text" name="username" placeholder="Filter by username" value="<?= htmlspecialchars($usernameFilter) ?>" class="logs_search_input">
        <button type="submit" class="logs_search_btn">Search</button>
    </form>

    <table>
        <tr>
            <th>User ID</th>
            <th>Username</th>
            <th>IP address</th>
            <th>Browser</th>
            <th>Page</th>
            <th>Timestamp</th>
        </tr>
        <?php foreach ($pagedLogs as $log): ?>
            <tr>
                <td><?= $log['user_id'] ?? '-' ?></td>
                <td><?= $log['username'] ?? 'Anonymous' ?></td>
                <td><?= $log['ip_address'] ?></td>
                <td><?= $log['web_browser'] ?></td>
                <td><?= $log['page_name'] ?></td>
                <td><?= $log['access_timestamp'] ?></td>
            </tr>
        <?php endforeach; ?>
    </table>

    <!-- Pagination -->
    <div>
        <ul class="logs_pagination_container">
            <?php for ($i = 1; $i <= $totalPages; $i++): ?>
            <li class="log_pagination_li">
                <a href="?section=logs&page=<?= $i ?>&username=<?= urlencode($usernameFilter) ?>"
                    class="<?= $i == $currentPage ? 'pagination_selected' : 'pagination_not_selected' ?>">
                    <?= $i ?>
                </a>
            </li>
            
            <?php endfor; ?>
        </ul>
    </div>

</article>

</html>